#!/bin/bash
#
# write by Aguy

_echoT "#################### START ${_PARTDEV}"



########################################  MAIN

cmd="sudo apt install -y"


_echoT "------------------ base install"

packages="cython3 python3-pip"

$cmd $packages


########################################  END

_echoT "------------------ write ${_PARTDEV}"
_partadd ${_PARTDEV} $_FILE_DEV_DONE

_echoT "#################### END ${_PARTDEV}"


