#!/bin/bash
#
# write by Aguy

_echoT "#################### START ${_PARTDEV}"

########################################  MAIN

cmd="sudo pacman -S --noconfirm --needed"

_echoT "------------------ install"

$cmd dbeaver

########################################  END

_echoT "------------------ write ${_PARTDEV}"
_partadd ${_PARTDEV} $_FILE_DEV_DONE

_echoT "#################### END ${_PARTDEV}"


