#!/bin/bash
#
# write by Aguy


_echoT "#################### START ${_PART} / ${S_RELEASE_DESKTOP}"

# xprop WM_CLASS
########################################  MAIN

_echoT "------------------ nothing to do"


########################################  END

_echoT "------------------ write ${_PART}"
_partadd "${_PART}" "${S_FILE_INSTALL_DONE}"


_echoT "#################### END ${_PART} / ${S_RELEASE_DESKTOP}"

