#!/bin/bash
#
# write by Aguy

_echoT "#################### START ${_PARTDEV}"



########################  MAIN

cmd="sudo pacman -S --noconfirm --needed"


_echot "------------------ install"

$cmd firefox-developer-edition firefox-developer-edition-i18n-fr


########################  END

_echot "------------------ write ${_PARTDEV}"
_partadd ${_PARTDEV} $_FILE_DEV_DONE

_echoT "#################### END ${_PARTDEV}"


