#!/bin/bash
#
# write by Aguy

_echoT "#################### START ${_PARTDEV}"



########################  MAIN

cmd="sudo pacman -S --noconfirm --needed"


_echot "------------------ base install"

packages="cython python-pip"

$cmd $packages


########################  END

_echot "------------------ write ${_PARTDEV}"
_partadd ${_PARTDEV} $_FILE_DEV_DONE

_echoT "#################### END ${_PARTDEV}"


