#!/bin/bash
#
# write by Aguy

_echoT "#################### START ${_PARTDEV}"

########################  DATA

path_opt=/opt/smartgit_${_SMARTGIT_VER}
path_conf=.config/smartgit
path_desk=~/.local/share/applications
file_desk=${path_desk}/smartgit.desktop
file_bin="/usr/bin/smartgit"


########################  MAIN

_echot "------------------ backup"

if [ -d ${path_opt} ] || [ -d ~/${path_conf} ]; then
	tar czf ${_PATH_SOFT_BACKUP}/smartgit_backup_${_DATE}-$(date +%s).tar.gz ${path_opt} ~/${path_conf} ${file_desk} ${file_bin}
fi


_echot "------------------ clean instance"

# delete existing folder
for path in ${path_opt} ~/${path_conf} ${file_desk} ${file_bin}; do
	[ -e ${path} ] && rm -fR ${path}
done


####################  RESTORE

if [ "$_SMARTGIT_DATE" ]; then

	[ -h ~/dev ] || ln -s /home/shared/dev ~/dev
	${S_PATH_SCRIPT}/backup-soft --restore ${_SMARTGIT_DATE} smartgit


####################  FRESH INSTALL

elif [ "${_SMARTGIT_VER}" ]; then

	cd /tmp

	_echot "------------------ get"

	file="smartgit-linux-${_SMARTGIT_VER}.tar.gz"
	url="https://www.syntevo.com/downloads/smartgit/${file}"

	if [ -f "${_PATH_SOFT}/$file" ]; then
		cp "${_PATH_SOFT}/$file" "$file"
	else
		_ANSWER="$file"
		while ! curl -o "$_ANSWER" "$url"; do
			_ask "Unable to donwload:\n$url\nGive a good url to download $file\nConfirm"
			_SMARTGIT_VER="${_ANSWER}"
			file="smartgit-linux-${_SMARTGIT_VER}.tar.gz"
			url="https://www.syntevo.com/downloads/smartgit/${file}"
		done
		cp "$file" "${_PATH_SOFT}/"
	fi


	_echot "------------------ install"

	path="smartgit"
	[ -d "$path" ] && rm -fR "$path"
	tar xzf "$file"
	mv "$path" "${path_opt}"
	rm "$file"

fi


####################  COMMON

_echot "------------------ $file_bin bind"

[ -e "$file_bin" ] || [ -h "$file_bin" ] && sudo rm "$file_bin"
sudo ln -s "${path_opt}/squirrel-sql.sh" "$file_bin"


_echot "------------------ launcher"

file="${path_desk}"/smartgit.desktop
echo "[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=SmartGit
Keywords=git
Comment=Git-Client
Type=Application
Categories=Development;RevisionControl
Terminal=false
StartupWMClass=SmartGit
Exec=\"$path_opt/bin/smartgit.sh\" %u
MimeType=x-scheme-handler/git;x-scheme-handler/smartgit;x-scheme-handler/sourcetree;
Icon=${path_opt}/bin/smartgit_128.png
" > "$file"
chmod +x "$file"


########################  END

_echot "------------------ write ${_PARTDEV}"
_partadd "${_PARTDEV}" "$_FILE_DEV_DONE"

_echoT "#################### END ${_PARTDEV}"

<<KEEP

_echot "------------------ get deb"

file="smartgit-${_SMARTGIT_VER}.deb"
url="https://www.syntevo.com/downloads/smartgit/${file}"
filedown=/tmp/$file
if [ -f ${_PATH_SOFT}/$file ]; then
	cp -a ${_PATH_SOFT}/$file $filedown
else
	! wget "$url" -O $filedown && _exite "Error during downloading 'smartgit' with url:\n$url"
fi

_echot "------------------ logs"

userconfver="${_SMARTGIT_VER//_/.}" && userconfver="${userconfver%.*}" && userconfver="${userconf}/${userconfver}"
[ -f "$userconfver/log.txt" ] && mv "$userconfver/log.txt" "$diropt"
! [ -f "$diropt/log.txt" ] && touch "$diropt/log.txt"
! [ -d "$userconfver" ] && mkdir -p "$userconfver"
ln -sv "$diropt/log.txt" "$userconfver/log.txt"

KEEP
