#!/bin/bash
#
# write by Aguy

_echoT "#################### START ${_PARTDEV}"



########################  MAIN

_echot "------------------ unpack"

file=${_PATH_SOFT}/connectors.tar.gz
! [ -f "$file" ] && _exite "Unable to find file: $file"
sudo tar xzf "$file" -C /opt


########################  END

_echot "------------------ write ${_PARTDEV}"
_partadd ${_PARTDEV} $_FILE_DEV_DONE

_echoT "#################### END ${_PARTDEV}"

