#!/bin/bash
#
# write by Aguy


########################  MAIN

_echoT "\n==========================================  ${S_RELEASE_NAME}-${_PART}"


_echoT "------------------ update"

sudo apt update


_echoT "------------------ dist-upgrade"

sudo apt -y dist-upgrade


#_echoT "------------------ clean"

#sudo apt autoremove; sudo apt clean; sudo apt autoclean


########################  END

_echoT "===================== ${_PART} end"
_partadd "${_PART}" "${S_FILE_INSTALL_DONE}"


