#!/bin/bash
#
# write by Aguy

_echoT "#################### START ${_PARTDEV}"

########################  MAIN

sudo apt-add-repository -yn ppa:serge-rider/dbeaver-ce # dbeaver
sudo apt update

_echoT "------------------ install"

cmd="sudo apt install -y"

$cmd dbeaver-ce

########################  END

_echoT "------------------ write ${_PARTDEV}"
_partadd ${_PARTDEV} $_FILE_DEV_DONE

_echoT "#################### END ${_PARTDEV}"


