#!/bin/bash
#
# write by Aguy

_echoT "#################### START ${_PART}DEV"

########################################  MAIN

sudo add-apt-repository -yn ppa:serge-rider/dbeaver-ce # dbeaver

_echoT "------------------ install"

cmd="sudo apt install -y"

$cmd dbeaver-ce

########################################  END

_echoT "------------------ write ${_PART}DEV"
_partadd ${_PART}DEV $_FILE_DEV_DONE

_echoT "#################### END ${_PART}DEV"


