#!/bin/bash
#
# write by Aguy

_echoT "#################### START ${_PART}DEV"



########################################  MAIN

cmd="sudo apt install -y"


_echoT "------------------ base install"

packages="cython3 python3-pip"

$cmd $packages


########################################  END

_echoT "------------------ write ${_PART}DEV"
_partadd ${_PART}DEV $_FILE_DEV_DONE

_echoT "#################### END ${_PART}DEV"


