#!/bin/bash
#
# write by Aguy

_echoT "#################### START ${_PART}DEV"



########################################  MAIN

cmd="sudo pacman -S --noconfirm --needed"


_echoT "------------------ base install"

packages="cython python-pip"

$cmd $packages


########################################  END

_echoT "------------------ write ${_PART}DEV"
_partadd ${_PART}DEV $_FILE_DEV_DONE

_echoT "#################### END ${_PART}DEV"


