#!/bin/bash
#
# write by Aguy


########################  MAIN

_echoT "\n==========================================  ${S_RELEASE_ID}-${_PART}"


_echot "------------------ update"

sudo pacman -Syy --noconfirm


_echot "------------------ upgrade & downgrade"

sudo pacman -Suu --noconfirm


#_echot "------------------ clean"

#sudo pacman -Sc --noconfirm


########################  END

_echoT "===================== ${_PART} end"
_partadd "${_PART}" "${S_FILE_INSTALL_DONE}"

