#!/bin/bash
#
# write by Aguy


########################  MAIN

_echoT "\n==========================================  ${S_RELEASE_ID}-${_PART}"

_echot "------------------ update"

sudo apt update

_echot "------------------ dist-upgrade"

sudo apt -y dist-upgrade

#_echot "------------------ clean"

#sudo apt autoremove; sudo apt clean; sudo apt autoclean

########################  END

_echoT "===================== ${_PART} end"
_partadd "${_PART}" "${S_FILE_INSTALL_DONE}"

